apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sumanth
  name: sumanth
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
      - mountPath: /sumanth
        name: sumanth-volume
  - image: busybox
    name: busybox
    command: ["bin/sh", "-c"]
    args: ["sleep 1000"]
    volumeMounts:
      - mountPath: /sumanth_busybox
        name: sumanth-volume
  volumes:
    - name: sumanth-volume
      emptyDir:
        sizeLimit: 50Mi  
