apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: sumanth  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie 
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
      - image: nginx
        name: mealie
        ports:
        - containerPort: 80
         