apiVersion: v1
kind: Service
metadata:
  name: mealie-service
  namespace: sumanth
spec:
  selector:
    app: mealie
  ports:
  - port: 80
    targetPort: 80
  # type: ClusterIP   # internal only (good for port-forward)
  type: LoadBalancer  # external access (if supported by the cluster)
